name: 🐛 Bug Report
description: Report an Issue or Bug
title: "[Bug]: "
labels: [ "bug" ]
assignees: [ "pascalkleindienst" ]
body:
  - type: markdown
    attributes:
      value: |
        We're sorry to hear you have a problem. Can you help us solve it by providing the following details.
  - type: checkboxes
    id: read-troubleshooting-guide
    attributes:
      label: Read the Troubleshooting guide.
      description: Please confirm that you've read and followed the [Troubleshooting guide](https://pascalkleindienst.github.io/fiov/guide/troubleshooting.html) before filing this bug report.
      options:
        - label: I have read and followed the Troubleshooting guide
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: I cannot currently do X thing because when I do, it breaks X thing.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the bug
      description: How did this occur, please provide a step-by-step guide.
      value: |
        1.
        2.
        3.
        4. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of our Package are you running? Please be as specific as possible
      placeholder: 2.0.0
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you running? Please be as specific as possible
      placeholder: 8.2.0
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Use this field to provide any other notes that you feel might be relevant to the issue.
      value: |
        - **Server OS**:
        - **Database**:
        - **Node version**:
        - **Browser & device**:
        - **Additional context**:
    validations:
      required: false
