name: 💡 Feature Request
description: I have a suggestion (and may want to implement it 🙂)!
title: "[FR]: "
labels: [ "feature" ]
assignees: [ "pascalkleindienst" ]
body:
  - type: textarea
    id: desc
    attributes:
      label: Feature
      description: A clear and concise description of the new feature or improvement.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any other information you think might be helpful, e.g. the motivation behind the feature, the benefits it brings, or examples of how it's been implemented elsewhere.
